spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi